### ISSUE TITLE
When attempting to use the error occurred not found AttachmentInterface

### ISSUE THREAD

**Issue by GabrielApG** [daniel-de-wit/nova-paperclip#1]
_Argument 1 passed to DanielDeWit\NovaPaperclip\PaperclipImage::DanielDeWit\NovaPaperclip\{closure}() must be an instance of Czim\Paperclip\Contracts\AttachmentInterface, string given_

We can place the package "laravel-paperclip" as a dependency of the composer or insert the class together with the "new-paperclip" package.

**Comment by daniel-de-wit** [comment]
Sorry for the late response. I've added the dependency to composer, like you suggested.
